name: CI

on:
  push:
    branches: ["dev", "stage", "main"]
  pull_request:
    branches: ["dev", "stage", "main"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install npm dependencies
        run: |
          npm pkg delete dependencies["@utexo/rgb-lib-wasm"]
          npm pkg delete dependencies["@utexo/rgb-sdk-core"]
          npm install @utexo/rgb-lib-wasm@latest @utexo/rgb-sdk-core@latest
          npm install
      - run: npm run lint

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install npm dependencies
        run: |
          npm pkg delete dependencies["@utexo/rgb-lib-wasm"]
          npm pkg delete dependencies["@utexo/rgb-sdk-core"]
          npm install @utexo/rgb-lib-wasm@latest @utexo/rgb-sdk-core@latest
          npm install
      - run: npx tsc --noEmit

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install npm dependencies
        run: |
          npm pkg delete dependencies["@utexo/rgb-lib-wasm"]
          npm pkg delete dependencies["@utexo/rgb-sdk-core"]
          npm install @utexo/rgb-lib-wasm@latest @utexo/rgb-sdk-core@latest
          npm install
      - run: npm run build
